---
title: "Boxplots vs. Barplots"
output: html_document
---

# Introduction

I am an unapologetic lover of boxplots, and as such I also am an unapologetic hater of barplots. Yet, about 90% of the time I'm asked to help someone make a figure in R, or more specificially in ggplot2, I'm asked for a barplot. So, this blog post is dedicated to why I think whenever possible you should use a boxplot over a barplot. If I've convinced you there's a handy summary provided at the end of the post that you can print out and distribute to any current barplot users.

**TAKE AWAY POINTS FROM THIS POST**

* Histograms are the best way to see the spread of your data.

* Boxplots are the next best way.

* Barplots are the worst way. Don't use them.


# Data

For today's post I've created two sets of make data, both of them have the same mean (XX) and the same standard deviation (XX), but as we'll see they are very different in terms of their distributions.


# Plots

## Histrogram

## Boxplot

## Barplot


# Conclusion

Don't use barplots.



